[project]
name = "deep-research-agent"
version = "0.1.0"
description = "An open source local deep research agent"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "Johannes Schießl", email = "contact.johannes@icloud.com" }]
requires-python = ">=3.12"
dependencies = []
